name: test-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - numba
  - scipy
  - pandas
  - dask
  - pyorbital
  - pyresample
  - satpy
  - netcdf4
  - gdal
  - click
  - appdirs
  - requests